openapi: 3.0.0
info:
  title: httpbin
  version: "0.1"
paths:
  /geta:
    get:
      operationId: /get
      responses: 
        "200":
          description: "get: response 200"
  /post:
    post:
      operationId: /post
      responses: 
        "200":
          description: "post: response 200"
servers:
  - url: https://httpbin.konghq.org